import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NotificationProvider } from '@/components/NotificationProvider';
import "./globals.css";
import Script from 'next/script'
import RealtimeNotifier from "@/components/RealtimeNotifier";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <RealtimeNotifier />
          {children}
          <Toaster position="top-right" richColors />

        <Script
          src={process.env.NODE_ENV === 'production' 
            ? "https://app.midtrans.com/snap/snap.js" 
            : "https://app.sandbox.midtrans.com/snap/snap.js"
          }
          data-client-key="SB-Mid-client-pQvIg9dYoy5mliYR"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}
